name: Cleanup Old Workflow Runs

on:
  schedule:
    # Run daily at 00:00 UTC (08:00 Beijing time)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  # Keep latest 5 runs for release workflows
  cleanup-release-workflows:
    name: Cleanup Release Workflows
    runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      matrix:
        workflow: ["SDK Release", "Release Agent", "Apps Release"]
    steps:
      - name: Delete old runs for ${{ matrix.workflow }}
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 5
          delete_workflow_pattern: "^${{ matrix.workflow }}$"

  # Delete all runs for other workflows
  cleanup-other-workflows:
    name: Cleanup Other Workflows
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old Test workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
          delete_workflow_pattern: "^Test$"

      - name: Delete old Auto Tag workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
          delete_workflow_pattern: "^Auto Tag Release$"

      - name: Delete old Cleanup workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
          delete_workflow_pattern: "^Cleanup Old Workflow Runs$"

