name: Cleanup Old Workflow Runs

on:
  schedule:
    # Run daily at 00:00 UTC (08:00 Beijing time)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    name: Cleanup Workflow Runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      # Release workflows - keep 5
      - name: Cleanup SDK Release
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 5
          delete_workflow_pattern: sdk-release.yml

      - name: Cleanup Release Agent
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 5
          delete_workflow_pattern: release.yml

      - name: Cleanup Apps Release
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 5
          delete_workflow_pattern: apps-release.yml

      # Other workflows - keep fewer
      - name: Cleanup Test
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
          delete_workflow_pattern: test.yml

      - name: Cleanup Auto Tag
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
          delete_workflow_pattern: auto-tag.yml

      - name: Cleanup self
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
          delete_workflow_pattern: cleanup.yml
